// opC

#include <stdio.h>

// These symbols are normally generated by ld/2. When we are being compiled
// with ld/1, there's nothing to generate them so we define them ourselves.
void* __constructors[1];
void* __destructors[1];

int main(void) {
	printf("Hello, world!\n");
	return 0;
}
