#!/bin/bash

set -e

if [[ -z "$ONRAMP_BIN" ]]; then
    echo "Error: ONRAMP_BIN is not set or is empty." >&2
    exit 1
fi

pushd ../src/mkfs
./build.sh
popd

pushd ../src/os
./build.sh
popd

pushd ../src/ed
./build.sh
popd

$ONRAMP_BIN/onrampvm ../src/mkfs/mkfs ../sd.img \
    ../src/os/shell.oe:shell.oe \
    ../src/ed/ed.oe:ed.oe \
    \
    ../extra/build-ccargs:build-ccargs \
    ../extra/main.c:main.c \
    ../extra/build.sh:build.sh \
    \
    $ONRAMP_BIN/../../intermediate/hex-0-onramp/hex.oe:hex.oe \
    $ONRAMP_BIN/../../intermediate/sh/sh.oe:sh.oe \
    \
    $ONRAMP_BIN/../../../core/sh/sh.oe.ohx:core/sh/sh.oe.ohx \
    \
    $ONRAMP_BIN/../../../core/build.sh:core/build.sh \
    $ONRAMP_BIN/../../../core/ld/0-global/build.sh:core/ld/0-global/build.sh \
    $ONRAMP_BIN/../../../core/ld/0-global/ld.oe.ohx:core/ld/0-global/ld.oe.ohx \
    $ONRAMP_BIN/../../../core/libc/0-oo/build.sh:core/libc/0-oo/build.sh \
    $ONRAMP_BIN/../../../core/libc/0-oo/src/start.oo:core/libc/0-oo/src/start.oo \
    $ONRAMP_BIN/../../../core/libc/0-oo/src/ctype.oo:core/libc/0-oo/src/ctype.oo \
    $ONRAMP_BIN/../../../core/libc/0-oo/src/environ.oo:core/libc/0-oo/src/environ.oo \
    $ONRAMP_BIN/../../../core/libc/0-oo/src/errno.oo:core/libc/0-oo/src/errno.oo \
    $ONRAMP_BIN/../../../core/libc/0-oo/src/malloc.oo:core/libc/0-oo/src/malloc.oo \
    $ONRAMP_BIN/../../../core/libc/0-oo/src/malloc_util.oo:core/libc/0-oo/src/malloc_util.oo \
    $ONRAMP_BIN/../../../core/libc/0-oo/src/spawn.oo:core/libc/0-oo/src/spawn.oo \
    $ONRAMP_BIN/../../../core/libc/0-oo/src/stdio.oo:core/libc/0-oo/src/stdio.oo \
    $ONRAMP_BIN/../../../core/libc/0-oo/src/string.oo:core/libc/0-oo/src/string.oo \
    $ONRAMP_BIN/../../../core/libo/0-oo/build.sh:core/libo/0-oo/build.sh \
    $ONRAMP_BIN/../../../core/libo/0-oo/src/libo-error.oo:core/libo/0-oo/src/libo-error.oo \
    $ONRAMP_BIN/../../../core/libo/0-oo/src/libo-util.oo:core/libo/0-oo/src/libo-util.oo \
    $ONRAMP_BIN/../../../core/ar/0-cat/build.sh:core/ar/0-cat/build.sh \
    $ONRAMP_BIN/../../../core/ar/0-cat/ar.oo:core/ar/0-cat/ar.oo \
    $ONRAMP_BIN/../../../core/as/0-basic/build.sh:core/as/0-basic/build.sh \
    $ONRAMP_BIN/../../../core/as/0-basic/as.oo:core/as/0-basic/as.oo \
    $ONRAMP_BIN/../../../core/as/1-compound/build.sh:core/as/1-compound/build.sh \
    $ONRAMP_BIN/../../../core/as/1-compound/src/emit.os:core/as/1-compound/src/emit.os \
    $ONRAMP_BIN/../../../core/as/1-compound/src/main.os:core/as/1-compound/src/main.os \
    $ONRAMP_BIN/../../../core/as/1-compound/src/op_arithmetic.os:core/as/1-compound/src/op_arithmetic.os \
    $ONRAMP_BIN/../../../core/as/1-compound/src/op_control.os:core/as/1-compound/src/op_control.os \
    $ONRAMP_BIN/../../../core/as/1-compound/src/op_logic.os:core/as/1-compound/src/op_logic.os \
    $ONRAMP_BIN/../../../core/as/1-compound/src/op_memory.os:core/as/1-compound/src/op_memory.os \
    $ONRAMP_BIN/../../../core/as/1-compound/src/opcodes.os:core/as/1-compound/src/opcodes.os \
    $ONRAMP_BIN/../../../core/as/1-compound/src/parse.os:core/as/1-compound/src/parse.os \
    $ONRAMP_BIN/../../../core/cpp/0-strip/build.sh:core/cpp/0-strip/build.sh \
    $ONRAMP_BIN/../../../core/cpp/0-strip/cpp.os:core/cpp/0-strip/cpp.os \
    $ONRAMP_BIN/../../../core/cci/0-omc/build.sh:core/cci/0-omc/build.sh \
    $ONRAMP_BIN/../../../core/cci/0-omc/src/common.os:core/cci/0-omc/src/common.os \
    $ONRAMP_BIN/../../../core/cci/0-omc/src/compile.os:core/cci/0-omc/src/compile.os \
    $ONRAMP_BIN/../../../core/cci/0-omc/src/emit.os:core/cci/0-omc/src/emit.os \
    $ONRAMP_BIN/../../../core/cci/0-omc/src/globals.os:core/cci/0-omc/src/globals.os \
    $ONRAMP_BIN/../../../core/cci/0-omc/src/lexer.os:core/cci/0-omc/src/lexer.os \
    $ONRAMP_BIN/../../../core/cci/0-omc/src/locals.os:core/cci/0-omc/src/locals.os \
    $ONRAMP_BIN/../../../core/cci/0-omc/src/main.os:core/cci/0-omc/src/main.os \
    $ONRAMP_BIN/../../../core/cci/0-omc/src/parse.os:core/cci/0-omc/src/parse.os \
    $ONRAMP_BIN/../../../core/cci/0-omc/src/type.os:core/cci/0-omc/src/type.os \
    $ONRAMP_BIN/../../../core/cpp/1-omc/build.sh:core/cpp/1-omc/build.sh \
    $ONRAMP_BIN/../../../core/cpp/1-omc/cpp.c:core/cpp/1-omc/cpp.c \
    \
    $ONRAMP_BIN/../../../core/libc/common/include/time.h:core/libc/common/include/time.h \
    $ONRAMP_BIN/../../../core/libc/common/include/stdalign.h:core/libc/common/include/stdalign.h \
    $ONRAMP_BIN/../../../core/libc/common/include/semaphore.h:core/libc/common/include/semaphore.h \
    $ONRAMP_BIN/../../../core/libc/common/include/inttypes.h:core/libc/common/include/inttypes.h \
    $ONRAMP_BIN/../../../core/libc/common/include/stdlib.h:core/libc/common/include/stdlib.h \
    $ONRAMP_BIN/../../../core/libc/common/include/stdnoreturn.h:core/libc/common/include/stdnoreturn.h \
    $ONRAMP_BIN/../../../core/libc/common/include/malloc.h:core/libc/common/include/malloc.h \
    $ONRAMP_BIN/../../../core/libc/common/include/features.h:core/libc/common/include/features.h \
    $ONRAMP_BIN/../../../core/libc/common/include/limits.h:core/libc/common/include/limits.h \
    $ONRAMP_BIN/../../../core/libc/common/include/unistd.h:core/libc/common/include/unistd.h \
    $ONRAMP_BIN/../../../core/libc/common/include/stddef.h:core/libc/common/include/stddef.h \
    $ONRAMP_BIN/../../../core/libc/common/include/wctype.h:core/libc/common/include/wctype.h \
    $ONRAMP_BIN/../../../core/libc/common/include/fcntl.h:core/libc/common/include/fcntl.h \
    $ONRAMP_BIN/../../../core/libc/common/include/signal.h:core/libc/common/include/signal.h \
    $ONRAMP_BIN/../../../core/libc/common/include/spawn.h:core/libc/common/include/spawn.h \
    $ONRAMP_BIN/../../../core/libc/common/include/setjmp.h:core/libc/common/include/setjmp.h \
    $ONRAMP_BIN/../../../core/libc/common/include/strings.h:core/libc/common/include/strings.h \
    $ONRAMP_BIN/../../../core/libc/common/include/sys/time.h:core/libc/common/include/sys/time.h \
    $ONRAMP_BIN/../../../core/libc/common/include/sys/types.h:core/libc/common/include/sys/types.h \
    $ONRAMP_BIN/../../../core/libc/common/include/sys/stat.h:core/libc/common/include/sys/stat.h \
    $ONRAMP_BIN/../../../core/libc/common/include/sys/syscall.h:core/libc/common/include/sys/syscall.h \
    $ONRAMP_BIN/../../../core/libc/common/include/stdckdint.h:core/libc/common/include/stdckdint.h \
    $ONRAMP_BIN/../../../core/libc/common/include/ctype.h:core/libc/common/include/ctype.h \
    $ONRAMP_BIN/../../../core/libc/common/include/__onramp/__seek.h:core/libc/common/include/__onramp/__seek.h \
    $ONRAMP_BIN/../../../core/libc/common/include/__onramp/__wint_t.h:core/libc/common/include/__onramp/__wint_t.h \
    $ONRAMP_BIN/../../../core/libc/common/include/__onramp/__size_t.h:core/libc/common/include/__onramp/__size_t.h \
    $ONRAMP_BIN/../../../core/libc/common/include/__onramp/__mode_t.h:core/libc/common/include/__onramp/__mode_t.h \
    $ONRAMP_BIN/../../../core/libc/common/include/__onramp/__time_t.h:core/libc/common/include/__onramp/__time_t.h \
    $ONRAMP_BIN/../../../core/libc/common/include/__onramp/__fatal.h:core/libc/common/include/__onramp/__fatal.h \
    $ONRAMP_BIN/../../../core/libc/common/include/__onramp/__null.h:core/libc/common/include/__onramp/__null.h \
    $ONRAMP_BIN/../../../core/libc/common/include/__onramp/__predef.h:core/libc/common/include/__onramp/__predef.h \
    $ONRAMP_BIN/../../../core/libc/common/include/__onramp/__bool.h:core/libc/common/include/__onramp/__bool.h \
    $ONRAMP_BIN/../../../core/libc/common/include/__onramp/__wchar_t.h:core/libc/common/include/__onramp/__wchar_t.h \
    $ONRAMP_BIN/../../../core/libc/common/include/__onramp/__timespec.h:core/libc/common/include/__onramp/__timespec.h \
    $ONRAMP_BIN/../../../core/libc/common/include/__onramp/__useconds_t.h:core/libc/common/include/__onramp/__useconds_t.h \
    $ONRAMP_BIN/../../../core/libc/common/include/__onramp/__pit.h:core/libc/common/include/__onramp/__pit.h \
    $ONRAMP_BIN/../../../core/libc/common/include/__onramp/__syscalls.h:core/libc/common/include/__onramp/__syscalls.h \
    $ONRAMP_BIN/../../../core/libc/common/include/__onramp/__va_list.h:core/libc/common/include/__onramp/__va_list.h \
    $ONRAMP_BIN/../../../core/libc/common/include/__onramp/__arithmetic.h:core/libc/common/include/__onramp/__arithmetic.h \
    $ONRAMP_BIN/../../../core/libc/common/include/__onramp/__wchar_limits.h:core/libc/common/include/__onramp/__wchar_limits.h \
    $ONRAMP_BIN/../../../core/libc/common/include/wchar.h:core/libc/common/include/wchar.h \
    $ONRAMP_BIN/../../../core/libc/common/include/stdbool.h:core/libc/common/include/stdbool.h \
    $ONRAMP_BIN/../../../core/libc/common/include/uchar.h:core/libc/common/include/uchar.h \
    $ONRAMP_BIN/../../../core/libc/common/include/iso646.h:core/libc/common/include/iso646.h \
    $ONRAMP_BIN/../../../core/libc/common/include/math.h:core/libc/common/include/math.h \
    $ONRAMP_BIN/../../../core/libc/common/include/errno.h:core/libc/common/include/errno.h \
    $ONRAMP_BIN/../../../core/libc/common/include/termios.h:core/libc/common/include/termios.h \
    $ONRAMP_BIN/../../../core/libc/common/include/stdbit.h:core/libc/common/include/stdbit.h \
    $ONRAMP_BIN/../../../core/libc/common/include/stdio.h:core/libc/common/include/stdio.h \
    $ONRAMP_BIN/../../../core/libc/common/include/stdarg.h:core/libc/common/include/stdarg.h \
    $ONRAMP_BIN/../../../core/libc/common/include/assert.h:core/libc/common/include/assert.h \
    $ONRAMP_BIN/../../../core/libc/common/include/stdint.h:core/libc/common/include/stdint.h \
    $ONRAMP_BIN/../../../core/libc/common/include/string.h:core/libc/common/include/string.h \
    \
    $ONRAMP_BIN/../../../core/libo/0-oo/include/libo-error.h:core/libo/0-oo/include/libo-error.h \
    $ONRAMP_BIN/../../../core/libo/0-oo/include/libo-util.h:core/libo/0-oo/include/libo-util.h \
    \
    $ONRAMP_BIN/../../../core/cg/0-asm/build.sh:core/cg/0-asm/build.sh \
    $ONRAMP_BIN/../../../core/cg/0-asm/src/common.h:core/cg/0-asm/src/common.h \
    $ONRAMP_BIN/../../../core/cg/0-asm/src/instruction.h:core/cg/0-asm/src/instruction.h \
    $ONRAMP_BIN/../../../core/cg/0-asm/src/main.c:core/cg/0-asm/src/main.c \
    $ONRAMP_BIN/../../../core/cg/0-asm/src/opcode.h:core/cg/0-asm/src/opcode.h \
    $ONRAMP_BIN/../../../core/cg/0-asm/src/optimize.h:core/cg/0-asm/src/optimize.h \
    $ONRAMP_BIN/../../../core/cg/0-asm/src/parse.h:core/cg/0-asm/src/parse.h \
    $ONRAMP_BIN/../../../core/cg/0-asm/src/register.h:core/cg/0-asm/src/register.h \
    $ONRAMP_BIN/../../../core/cpp/1-omc/rebuild.sh:core/cpp/1-omc/rebuild.sh \
    $ONRAMP_BIN/../../../core/ld/1-omc/build.sh:core/ld/1-omc/build.sh \
    $ONRAMP_BIN/../../../core/ld/1-omc/ld.c:core/ld/1-omc/ld.c \
    \
    $ONRAMP_BIN/../../../core/libc/common/src/internal.h:core/libc/common/src/internal.h \
    \
    $ONRAMP_BIN/../../../core/libc/1-omc/build.sh:core/libc/1-omc/build.sh \
    $ONRAMP_BIN/../../../core/libc/1-omc/src/strrchr.c:core/libc/1-omc/src/strrchr.c \
    $ONRAMP_BIN/../../../core/libc/1-omc/src/strtol.c:core/libc/1-omc/src/strtol.c \
    $ONRAMP_BIN/../../../core/cc/build.sh:core/cc/build.sh \
    $ONRAMP_BIN/../../../core/cc/cc.c:core/cc/cc.c \
    $ONRAMP_BIN/../../../core/cci/1-opc/build.sh:core/cci/1-opc/build.sh \
    $ONRAMP_BIN/../../../core/cci/1-opc/build-ccargs:core/cci/1-opc/build-ccargs \
    $ONRAMP_BIN/../../../core/cci/1-opc/src/common.c:core/cci/1-opc/src/common.c \
    $ONRAMP_BIN/../../../core/cci/1-opc/src/common.h:core/cci/1-opc/src/common.h \
    $ONRAMP_BIN/../../../core/cci/1-opc/src/compile.c:core/cci/1-opc/src/compile.c \
    $ONRAMP_BIN/../../../core/cci/1-opc/src/compile.h:core/cci/1-opc/src/compile.h \
    $ONRAMP_BIN/../../../core/cci/1-opc/src/emit.c:core/cci/1-opc/src/emit.c \
    $ONRAMP_BIN/../../../core/cci/1-opc/src/emit.h:core/cci/1-opc/src/emit.h \
    $ONRAMP_BIN/../../../core/cci/1-opc/src/global.c:core/cci/1-opc/src/global.c \
    $ONRAMP_BIN/../../../core/cci/1-opc/src/global.h:core/cci/1-opc/src/global.h \
    $ONRAMP_BIN/../../../core/cci/1-opc/src/lexer.c:core/cci/1-opc/src/lexer.c \
    $ONRAMP_BIN/../../../core/cci/1-opc/src/lexer.h:core/cci/1-opc/src/lexer.h \
    $ONRAMP_BIN/../../../core/cci/1-opc/src/locals.c:core/cci/1-opc/src/locals.c \
    $ONRAMP_BIN/../../../core/cci/1-opc/src/locals.h:core/cci/1-opc/src/locals.h \
    $ONRAMP_BIN/../../../core/cci/1-opc/src/main.c:core/cci/1-opc/src/main.c \
    $ONRAMP_BIN/../../../core/cci/1-opc/src/member.c:core/cci/1-opc/src/member.c \
    $ONRAMP_BIN/../../../core/cci/1-opc/src/member.h:core/cci/1-opc/src/member.h \
    $ONRAMP_BIN/../../../core/cci/1-opc/src/parse-decl.c:core/cci/1-opc/src/parse-decl.c \
    $ONRAMP_BIN/../../../core/cci/1-opc/src/parse-decl.h:core/cci/1-opc/src/parse-decl.h \
    $ONRAMP_BIN/../../../core/cci/1-opc/src/parse-expr.c:core/cci/1-opc/src/parse-expr.c \
    $ONRAMP_BIN/../../../core/cci/1-opc/src/parse-expr.h:core/cci/1-opc/src/parse-expr.h \
    $ONRAMP_BIN/../../../core/cci/1-opc/src/parse-stmt.c:core/cci/1-opc/src/parse-stmt.c \
    $ONRAMP_BIN/../../../core/cci/1-opc/src/parse-stmt.h:core/cci/1-opc/src/parse-stmt.h \
    $ONRAMP_BIN/../../../core/cci/1-opc/src/record.c:core/cci/1-opc/src/record.c \
    $ONRAMP_BIN/../../../core/cci/1-opc/src/record.h:core/cci/1-opc/src/record.h \
    $ONRAMP_BIN/../../../core/cci/1-opc/src/type.c:core/cci/1-opc/src/type.c \
    $ONRAMP_BIN/../../../core/cci/1-opc/src/type.h:core/cci/1-opc/src/type.h \
    $ONRAMP_BIN/../../../core/cci/1-opc/src/types.c:core/cci/1-opc/src/types.c \
    $ONRAMP_BIN/../../../core/cci/1-opc/src/types.h:core/cci/1-opc/src/types.h \
    $ONRAMP_BIN/../../../core/libc/2-opc/build.sh:core/libc/2-opc/build.sh \
    $ONRAMP_BIN/../../../core/libc/2-opc/build-ccargs:core/libc/2-opc/build-ccargs \
    $ONRAMP_BIN/../../../core/libc/2-opc/src/assert.c:core/libc/2-opc/src/assert.c \
    $ONRAMP_BIN/../../../core/libc/2-opc/src/ctype.c:core/libc/2-opc/src/ctype.c \
    $ONRAMP_BIN/../../../core/libc/2-opc/src/environ.c:core/libc/2-opc/src/environ.c \
    $ONRAMP_BIN/../../../core/libc/2-opc/src/float.c:core/libc/2-opc/src/float.c \
    $ONRAMP_BIN/../../../core/libc/2-opc/src/format.c:core/libc/2-opc/src/format.c \
    $ONRAMP_BIN/../../../core/libc/2-opc/src/llong.c:core/libc/2-opc/src/llong.c \
    $ONRAMP_BIN/../../../core/libc/2-opc/src/multibyte.c:core/libc/2-opc/src/multibyte.c \
    $ONRAMP_BIN/../../../core/libc/2-opc/src/posixio.c:core/libc/2-opc/src/posixio.c \
    $ONRAMP_BIN/../../../core/libc/2-opc/src/setjmp.os:core/libc/2-opc/src/setjmp.os \
    $ONRAMP_BIN/../../../core/libc/2-opc/src/start.os:core/libc/2-opc/src/start.os \
    $ONRAMP_BIN/../../../core/libc/2-opc/src/stdbit.c:core/libc/2-opc/src/stdbit.c \
    $ONRAMP_BIN/../../../core/libc/2-opc/src/stdio.c:core/libc/2-opc/src/stdio.c \
    $ONRAMP_BIN/../../../core/libc/2-opc/src/stdlib.c:core/libc/2-opc/src/stdlib.c \
    $ONRAMP_BIN/../../../core/libc/2-opc/src/string.c:core/libc/2-opc/src/string.c \
    $ONRAMP_BIN/../../../core/libc/2-opc/src/strings.c:core/libc/2-opc/src/strings.c \
    $ONRAMP_BIN/../../../core/libc/2-opc/src/stubs.c:core/libc/2-opc/src/stubs.c \
    $ONRAMP_BIN/../../../core/libc/2-opc/src/syscalls.os:core/libc/2-opc/src/syscalls.os \
    $ONRAMP_BIN/../../../core/libc/2-opc/src/system.c:core/libc/2-opc/src/system.c \
    $ONRAMP_BIN/../../../core/libo/1-opc/build.sh:core/libo/1-opc/build.sh \
    $ONRAMP_BIN/../../../core/libo/1-opc/build-ccargs:core/libo/1-opc/build-ccargs \
    $ONRAMP_BIN/../../../core/libo/1-opc/include/libo-error.h:core/libo/1-opc/include/libo-error.h \
    $ONRAMP_BIN/../../../core/libo/1-opc/include/libo-reader.h:core/libo/1-opc/include/libo-reader.h \
    $ONRAMP_BIN/../../../core/libo/1-opc/include/libo-string.h:core/libo/1-opc/include/libo-string.h \
    $ONRAMP_BIN/../../../core/libo/1-opc/include/libo-table.h:core/libo/1-opc/include/libo-table.h \
    $ONRAMP_BIN/../../../core/libo/1-opc/include/libo-unicode.h:core/libo/1-opc/include/libo-unicode.h \
    $ONRAMP_BIN/../../../core/libo/1-opc/include/libo-util.h:core/libo/1-opc/include/libo-util.h \
    $ONRAMP_BIN/../../../core/libo/1-opc/include/libo-vector.h:core/libo/1-opc/include/libo-vector.h \
    $ONRAMP_BIN/../../../core/libo/1-opc/src/libo-data.os:core/libo/1-opc/src/libo-data.os \
    $ONRAMP_BIN/../../../core/libo/1-opc/src/libo-error.c:core/libo/1-opc/src/libo-error.c \
    $ONRAMP_BIN/../../../core/libo/1-opc/src/libo-reader.c:core/libo/1-opc/src/libo-reader.c \
    $ONRAMP_BIN/../../../core/libo/1-opc/src/libo-string.c:core/libo/1-opc/src/libo-string.c \
    $ONRAMP_BIN/../../../core/libo/1-opc/src/libo-table.c:core/libo/1-opc/src/libo-table.c \
    $ONRAMP_BIN/../../../core/libo/1-opc/src/libo-unicode.c:core/libo/1-opc/src/libo-unicode.c \
    $ONRAMP_BIN/../../../core/libo/1-opc/src/libo-util.c:core/libo/1-opc/src/libo-util.c \
    $ONRAMP_BIN/../../../core/libo/1-opc/src/libo-vector.c:core/libo/1-opc/src/libo-vector.c \
    $ONRAMP_BIN/../../../core/ld/2-full/build.sh:core/ld/2-full/build.sh \
    $ONRAMP_BIN/../../../core/ld/2-full/build-ccargs:core/ld/2-full/build-ccargs \
    $ONRAMP_BIN/../../../core/ld/2-full/src/common.c:core/ld/2-full/src/common.c \
    $ONRAMP_BIN/../../../core/ld/2-full/src/common.h:core/ld/2-full/src/common.h \
    $ONRAMP_BIN/../../../core/ld/2-full/src/emit.c:core/ld/2-full/src/emit.c \
    $ONRAMP_BIN/../../../core/ld/2-full/src/emit.h:core/ld/2-full/src/emit.h \
    $ONRAMP_BIN/../../../core/ld/2-full/src/label.c:core/ld/2-full/src/label.c \
    $ONRAMP_BIN/../../../core/ld/2-full/src/label.h:core/ld/2-full/src/label.h \
    $ONRAMP_BIN/../../../core/ld/2-full/src/main.c:core/ld/2-full/src/main.c \
    $ONRAMP_BIN/../../../core/ld/2-full/src/parse.c:core/ld/2-full/src/parse.c \
    $ONRAMP_BIN/../../../core/ld/2-full/src/parse.h:core/ld/2-full/src/parse.h \
    $ONRAMP_BIN/../../../core/ld/2-full/src/symbol.c:core/ld/2-full/src/symbol.c \
    $ONRAMP_BIN/../../../core/ld/2-full/src/symbol.h:core/ld/2-full/src/symbol.h \
    $ONRAMP_BIN/../../../core/cci/2-full/build.sh:core/cci/2-full/build.sh \
    $ONRAMP_BIN/../../../core/cci/2-full/build-ccargs:core/cci/2-full/build-ccargs \
    $ONRAMP_BIN/../../../core/cci/2-full/src/arithmetic.c:core/cci/2-full/src/arithmetic.c \
    $ONRAMP_BIN/../../../core/cci/2-full/src/arithmetic.h:core/cci/2-full/src/arithmetic.h \
    $ONRAMP_BIN/../../../core/cci/2-full/src/block.c:core/cci/2-full/src/block.c \
    $ONRAMP_BIN/../../../core/cci/2-full/src/block.h:core/cci/2-full/src/block.h \
    $ONRAMP_BIN/../../../core/cci/2-full/src/common.c:core/cci/2-full/src/common.c \
    $ONRAMP_BIN/../../../core/cci/2-full/src/common.h:core/cci/2-full/src/common.h \
    $ONRAMP_BIN/../../../core/cci/2-full/src/emit.c:core/cci/2-full/src/emit.c \
    $ONRAMP_BIN/../../../core/cci/2-full/src/emit.h:core/cci/2-full/src/emit.h \
    $ONRAMP_BIN/../../../core/cci/2-full/src/enum.c:core/cci/2-full/src/enum.c \
    $ONRAMP_BIN/../../../core/cci/2-full/src/enum.h:core/cci/2-full/src/enum.h \
    $ONRAMP_BIN/../../../core/cci/2-full/src/function.c:core/cci/2-full/src/function.c \
    $ONRAMP_BIN/../../../core/cci/2-full/src/function.h:core/cci/2-full/src/function.h \
    $ONRAMP_BIN/../../../core/cci/2-full/src/generate_ops.c:core/cci/2-full/src/generate_ops.c \
    $ONRAMP_BIN/../../../core/cci/2-full/src/generate_ops.h:core/cci/2-full/src/generate_ops.h \
    $ONRAMP_BIN/../../../core/cci/2-full/src/generate_stmt.c:core/cci/2-full/src/generate_stmt.c \
    $ONRAMP_BIN/../../../core/cci/2-full/src/generate_stmt.h:core/cci/2-full/src/generate_stmt.h \
    $ONRAMP_BIN/../../../core/cci/2-full/src/generate.c:core/cci/2-full/src/generate.c \
    $ONRAMP_BIN/../../../core/cci/2-full/src/generate.h:core/cci/2-full/src/generate.h \
    $ONRAMP_BIN/../../../core/cci/2-full/src/instruction.c:core/cci/2-full/src/instruction.c \
    $ONRAMP_BIN/../../../core/cci/2-full/src/instruction.h:core/cci/2-full/src/instruction.h \
    $ONRAMP_BIN/../../../core/cci/2-full/src/lexer.c:core/cci/2-full/src/lexer.c \
    $ONRAMP_BIN/../../../core/cci/2-full/src/lexer.h:core/cci/2-full/src/lexer.h \
    $ONRAMP_BIN/../../../core/cci/2-full/src/main.c:core/cci/2-full/src/main.c \
    $ONRAMP_BIN/../../../core/cci/2-full/src/node.c:core/cci/2-full/src/node.c \
    $ONRAMP_BIN/../../../core/cci/2-full/src/node.h:core/cci/2-full/src/node.h \
    $ONRAMP_BIN/../../../core/cci/2-full/src/optimize_asm.c:core/cci/2-full/src/optimize_asm.c \
    $ONRAMP_BIN/../../../core/cci/2-full/src/optimize_asm.h:core/cci/2-full/src/optimize_asm.h \
    $ONRAMP_BIN/../../../core/cci/2-full/src/optimize_tree.c:core/cci/2-full/src/optimize_tree.c \
    $ONRAMP_BIN/../../../core/cci/2-full/src/optimize_tree.h:core/cci/2-full/src/optimize_tree.h \
    $ONRAMP_BIN/../../../core/cci/2-full/src/options.c:core/cci/2-full/src/options.c \
    $ONRAMP_BIN/../../../core/cci/2-full/src/options.h:core/cci/2-full/src/options.h \
    $ONRAMP_BIN/../../../core/cci/2-full/src/parse_decl.c:core/cci/2-full/src/parse_decl.c \
    $ONRAMP_BIN/../../../core/cci/2-full/src/parse_decl.h:core/cci/2-full/src/parse_decl.h \
    $ONRAMP_BIN/../../../core/cci/2-full/src/parse_expr.c:core/cci/2-full/src/parse_expr.c \
    $ONRAMP_BIN/../../../core/cci/2-full/src/parse_expr.h:core/cci/2-full/src/parse_expr.h \
    $ONRAMP_BIN/../../../core/cci/2-full/src/parse_init.c:core/cci/2-full/src/parse_init.c \
    $ONRAMP_BIN/../../../core/cci/2-full/src/parse_init.h:core/cci/2-full/src/parse_init.h \
    $ONRAMP_BIN/../../../core/cci/2-full/src/parse_stmt.c:core/cci/2-full/src/parse_stmt.c \
    $ONRAMP_BIN/../../../core/cci/2-full/src/parse_stmt.h:core/cci/2-full/src/parse_stmt.h \
    $ONRAMP_BIN/../../../core/cci/2-full/src/record.c:core/cci/2-full/src/record.c \
    $ONRAMP_BIN/../../../core/cci/2-full/src/record.h:core/cci/2-full/src/record.h \
    $ONRAMP_BIN/../../../core/cci/2-full/src/scope.c:core/cci/2-full/src/scope.c \
    $ONRAMP_BIN/../../../core/cci/2-full/src/scope.h:core/cci/2-full/src/scope.h \
    $ONRAMP_BIN/../../../core/cci/2-full/src/strings.c:core/cci/2-full/src/strings.c \
    $ONRAMP_BIN/../../../core/cci/2-full/src/strings.h:core/cci/2-full/src/strings.h \
    $ONRAMP_BIN/../../../core/cci/2-full/src/symbol.c:core/cci/2-full/src/symbol.c \
    $ONRAMP_BIN/../../../core/cci/2-full/src/symbol.h:core/cci/2-full/src/symbol.h \
    $ONRAMP_BIN/../../../core/cci/2-full/src/token.c:core/cci/2-full/src/token.c \
    $ONRAMP_BIN/../../../core/cci/2-full/src/token.h:core/cci/2-full/src/token.h \
    $ONRAMP_BIN/../../../core/cci/2-full/src/type.c:core/cci/2-full/src/type.c \
    $ONRAMP_BIN/../../../core/cci/2-full/src/type.h:core/cci/2-full/src/type.h \
    $ONRAMP_BIN/../../../core/cpp/2-full/build.sh:core/cpp/2-full/build.sh \
    $ONRAMP_BIN/../../../core/cpp/2-full/build-ccargs:core/cpp/2-full/build-ccargs \
    $ONRAMP_BIN/../../../core/cpp/2-full/src/common.c:core/cpp/2-full/src/common.c \
    $ONRAMP_BIN/../../../core/cpp/2-full/src/common.h:core/cpp/2-full/src/common.h \
    $ONRAMP_BIN/../../../core/cpp/2-full/src/directive.c:core/cpp/2-full/src/directive.c \
    $ONRAMP_BIN/../../../core/cpp/2-full/src/directive.h:core/cpp/2-full/src/directive.h \
    $ONRAMP_BIN/../../../core/cpp/2-full/src/emit.c:core/cpp/2-full/src/emit.c \
    $ONRAMP_BIN/../../../core/cpp/2-full/src/emit.h:core/cpp/2-full/src/emit.h \
    $ONRAMP_BIN/../../../core/cpp/2-full/src/expression.c:core/cpp/2-full/src/expression.c \
    $ONRAMP_BIN/../../../core/cpp/2-full/src/expression.h:core/cpp/2-full/src/expression.h \
    $ONRAMP_BIN/../../../core/cpp/2-full/src/file.c:core/cpp/2-full/src/file.c \
    $ONRAMP_BIN/../../../core/cpp/2-full/src/file.h:core/cpp/2-full/src/file.h \
    $ONRAMP_BIN/../../../core/cpp/2-full/src/hideset.c:core/cpp/2-full/src/hideset.c \
    $ONRAMP_BIN/../../../core/cpp/2-full/src/hideset.h:core/cpp/2-full/src/hideset.h \
    $ONRAMP_BIN/../../../core/cpp/2-full/src/lexer.c:core/cpp/2-full/src/lexer.c \
    $ONRAMP_BIN/../../../core/cpp/2-full/src/lexer.h:core/cpp/2-full/src/lexer.h \
    $ONRAMP_BIN/../../../core/cpp/2-full/src/macro.c:core/cpp/2-full/src/macro.c \
    $ONRAMP_BIN/../../../core/cpp/2-full/src/macro.h:core/cpp/2-full/src/macro.h \
    $ONRAMP_BIN/../../../core/cpp/2-full/src/main.c:core/cpp/2-full/src/main.c \
    $ONRAMP_BIN/../../../core/cpp/2-full/src/options.c:core/cpp/2-full/src/options.c \
    $ONRAMP_BIN/../../../core/cpp/2-full/src/options.h:core/cpp/2-full/src/options.h \
    $ONRAMP_BIN/../../../core/cpp/2-full/src/preprocess.c:core/cpp/2-full/src/preprocess.c \
    $ONRAMP_BIN/../../../core/cpp/2-full/src/preprocess.h:core/cpp/2-full/src/preprocess.h \
    $ONRAMP_BIN/../../../core/cpp/2-full/src/stream.c:core/cpp/2-full/src/stream.c \
    $ONRAMP_BIN/../../../core/cpp/2-full/src/stream.h:core/cpp/2-full/src/stream.h \
    $ONRAMP_BIN/../../../core/cpp/2-full/src/strings.c:core/cpp/2-full/src/strings.c \
    $ONRAMP_BIN/../../../core/cpp/2-full/src/strings.h:core/cpp/2-full/src/strings.h \
    $ONRAMP_BIN/../../../core/cpp/2-full/src/token.c:core/cpp/2-full/src/token.c \
    $ONRAMP_BIN/../../../core/cpp/2-full/src/token.h:core/cpp/2-full/src/token.h \
    $ONRAMP_BIN/../../../core/libc/3-full/build.sh:core/libc/3-full/build.sh \
    $ONRAMP_BIN/../../../core/libc/3-full/build-ccargs:core/libc/3-full/build-ccargs \
    $ONRAMP_BIN/../../../core/libc/3-full/src/atexit.c:core/libc/3-full/src/atexit.c \
    $ONRAMP_BIN/../../../core/libc/3-full/src/bsearch.c:core/libc/3-full/src/bsearch.c \
    $ONRAMP_BIN/../../../core/libc/3-full/src/malloc.c:core/libc/3-full/src/malloc.c \
    $ONRAMP_BIN/../../../core/libc/3-full/src/qsort.c:core/libc/3-full/src/qsort.c \
    $ONRAMP_BIN/../../../core/libc/3-full/src/rand.c:core/libc/3-full/src/rand.c \
    $ONRAMP_BIN/../../../core/libc/3-full/src/signal.c:core/libc/3-full/src/signal.c \
    $ONRAMP_BIN/../../../core/libc/3-full/src/stdbit_llong.c:core/libc/3-full/src/stdbit_llong.c \
    $ONRAMP_BIN/../../../core/libc/3-full/src/stdlib_3.c:core/libc/3-full/src/stdlib_3.c \
    $ONRAMP_BIN/../../../core/libc/3-full/src/time.c:core/libc/3-full/src/time.c \
    $ONRAMP_BIN/../../../core/libc/3-full/src/strtol.c:core/libc/3-full/src/strtol.c \
    $ONRAMP_BIN/../../../core/as/2-full/build.sh:core/as/2-full/build.sh \
    $ONRAMP_BIN/../../../core/as/2-full/build-ccargs:core/as/2-full/build-ccargs \
    $ONRAMP_BIN/../../../core/as/2-full/src/common.c:core/as/2-full/src/common.c \
    $ONRAMP_BIN/../../../core/as/2-full/src/common.h:core/as/2-full/src/common.h \
    $ONRAMP_BIN/../../../core/as/2-full/src/emit.c:core/as/2-full/src/emit.c \
    $ONRAMP_BIN/../../../core/as/2-full/src/emit.h:core/as/2-full/src/emit.h \
    $ONRAMP_BIN/../../../core/as/2-full/src/main.c:core/as/2-full/src/main.c \
    $ONRAMP_BIN/../../../core/as/2-full/src/opcodes.c:core/as/2-full/src/opcodes.c \
    $ONRAMP_BIN/../../../core/as/2-full/src/opcodes.h:core/as/2-full/src/opcodes.h \
    $ONRAMP_BIN/../../../core/as/2-full/src/parse.c:core/as/2-full/src/parse.c \
    $ONRAMP_BIN/../../../core/as/2-full/src/parse.h:core/as/2-full/src/parse.h \
    $ONRAMP_BIN/../../../core/libc/common/build.sh:core/libc/common/build.sh \
    $ONRAMP_BIN/../../../core/libc/3-full/rebuild.sh:core/libc/3-full/rebuild.sh \
    $ONRAMP_BIN/../../../core/libc/3-full/rebuild-ccargs:core/libc/3-full/rebuild-ccargs \
    $ONRAMP_BIN/../../../core/libo/1-opc/rebuild.sh:core/libo/1-opc/rebuild.sh \
    $ONRAMP_BIN/../../../core/libo/1-opc/rebuild-ccargs:core/libo/1-opc/rebuild-ccargs \
    $ONRAMP_BIN/../../../core/cc/rebuild.sh:core/cc/rebuild.sh \
    ../extra/core/ld/2-full/rebuild.sh:core/ld/2-full/rebuild.sh \
    ../extra/core/ld/2-full/rebuild-ccargs:core/ld/2-full/rebuild-ccargs \
    ../extra/core/as/2-full/rebuild.sh:core/as/2-full/rebuild.sh \
    ../extra/core/as/2-full/rebuild-ccargs:core/as/2-full/rebuild-ccargs \
    ../extra/core/cci/2-full/rebuild.sh:core/cci/2-full/rebuild.sh \
    ../extra/core/cci/2-full/rebuild-ccargs:core/cci/2-full/rebuild-ccargs \
    ../extra/core/cpp/2-full/rebuild.sh:core/cpp/2-full/rebuild.sh \
    ../extra/core/cpp/2-full/rebuild-ccargs:core/cpp/2-full/rebuild-ccargs \
    ../extra/core/hex/1-c89/build.sh:core/hex/1-c89/build.sh \
    $ONRAMP_BIN/../../../core/hex/1-c89/hex.c:core/hex/1-c89/hex.c \
    \
    $ONRAMP_BIN/../../final/bin/cpp.oe:output/final/bin/cpp.oe \
    $ONRAMP_BIN/../../final/bin/cci.oe:output/final/bin/cci.oe \
    $ONRAMP_BIN/../../final/bin/ld.oe.od:output/final/bin/ld.oe.od \
    $ONRAMP_BIN/../../final/bin/ld.oe:output/final/bin/ld.oe \
    $ONRAMP_BIN/../../final/bin/hex.oe.od:output/final/bin/hex.oe.od \
    $ONRAMP_BIN/../../final/bin/cc.oe:output/final/bin/cc.oe \
    $ONRAMP_BIN/../../final/bin/as.oe.od:output/final/bin/as.oe.od \
    $ONRAMP_BIN/../../final/bin/cpp.oe.od:output/final/bin/cpp.oe.od \
    $ONRAMP_BIN/../../final/bin/cci.oe.od:output/final/bin/cci.oe.od \
    $ONRAMP_BIN/../../final/bin/as.oe:output/final/bin/as.oe \
    $ONRAMP_BIN/../../final/bin/hex.oe:output/final/bin/hex.oe \
    $ONRAMP_BIN/../../final/bin/ar.oe:output/final/bin/ar.oe \
    $ONRAMP_BIN/../../final/bin/cc.oe.od:output/final/bin/cc.oe.od \
    $ONRAMP_BIN/../../final/include/time.h:output/final/include/time.h \
    $ONRAMP_BIN/../../final/include/stdalign.h:output/final/include/stdalign.h \
    $ONRAMP_BIN/../../final/include/semaphore.h:output/final/include/semaphore.h \
    $ONRAMP_BIN/../../final/include/inttypes.h:output/final/include/inttypes.h \
    $ONRAMP_BIN/../../final/include/stdlib.h:output/final/include/stdlib.h \
    $ONRAMP_BIN/../../final/include/stdnoreturn.h:output/final/include/stdnoreturn.h \
    $ONRAMP_BIN/../../final/include/malloc.h:output/final/include/malloc.h \
    $ONRAMP_BIN/../../final/include/features.h:output/final/include/features.h \
    $ONRAMP_BIN/../../final/include/limits.h:output/final/include/limits.h \
    $ONRAMP_BIN/../../final/include/unistd.h:output/final/include/unistd.h \
    $ONRAMP_BIN/../../final/include/stddef.h:output/final/include/stddef.h \
    $ONRAMP_BIN/../../final/include/wctype.h:output/final/include/wctype.h \
    $ONRAMP_BIN/../../final/include/fcntl.h:output/final/include/fcntl.h \
    $ONRAMP_BIN/../../final/include/signal.h:output/final/include/signal.h \
    $ONRAMP_BIN/../../final/include/spawn.h:output/final/include/spawn.h \
    $ONRAMP_BIN/../../final/include/setjmp.h:output/final/include/setjmp.h \
    $ONRAMP_BIN/../../final/include/strings.h:output/final/include/strings.h \
    $ONRAMP_BIN/../../final/include/sys/time.h:output/final/include/sys/time.h \
    $ONRAMP_BIN/../../final/include/sys/types.h:output/final/include/sys/types.h \
    $ONRAMP_BIN/../../final/include/sys/stat.h:output/final/include/sys/stat.h \
    $ONRAMP_BIN/../../final/include/ctype.h:output/final/include/ctype.h \
    $ONRAMP_BIN/../../final/include/__onramp/__seek.h:output/final/include/__onramp/__seek.h \
    $ONRAMP_BIN/../../final/include/__onramp/__wint_t.h:output/final/include/__onramp/__wint_t.h \
    $ONRAMP_BIN/../../final/include/__onramp/__size_t.h:output/final/include/__onramp/__size_t.h \
    $ONRAMP_BIN/../../final/include/__onramp/__mode_t.h:output/final/include/__onramp/__mode_t.h \
    $ONRAMP_BIN/../../final/include/__onramp/__time_t.h:output/final/include/__onramp/__time_t.h \
    $ONRAMP_BIN/../../final/include/__onramp/__fatal.h:output/final/include/__onramp/__fatal.h \
    $ONRAMP_BIN/../../final/include/__onramp/__null.h:output/final/include/__onramp/__null.h \
    $ONRAMP_BIN/../../final/include/__onramp/__predef.h:output/final/include/__onramp/__predef.h \
    $ONRAMP_BIN/../../final/include/__onramp/__bool.h:output/final/include/__onramp/__bool.h \
    $ONRAMP_BIN/../../final/include/__onramp/__wchar_t.h:output/final/include/__onramp/__wchar_t.h \
    $ONRAMP_BIN/../../final/include/__onramp/__timespec.h:output/final/include/__onramp/__timespec.h \
    $ONRAMP_BIN/../../final/include/__onramp/__useconds_t.h:output/final/include/__onramp/__useconds_t.h \
    $ONRAMP_BIN/../../final/include/__onramp/__pit.h:output/final/include/__onramp/__pit.h \
    $ONRAMP_BIN/../../final/include/__onramp/__syscalls.h:output/final/include/__onramp/__syscalls.h \
    $ONRAMP_BIN/../../final/include/__onramp/__va_list.h:output/final/include/__onramp/__va_list.h \
    $ONRAMP_BIN/../../final/include/__onramp/__arithmetic.h:output/final/include/__onramp/__arithmetic.h \
    $ONRAMP_BIN/../../final/include/__onramp/__wchar_limits.h:output/final/include/__onramp/__wchar_limits.h \
    $ONRAMP_BIN/../../final/include/wchar.h:output/final/include/wchar.h \
    $ONRAMP_BIN/../../final/include/stdbool.h:output/final/include/stdbool.h \
    $ONRAMP_BIN/../../final/include/uchar.h:output/final/include/uchar.h \
    $ONRAMP_BIN/../../final/include/iso646.h:output/final/include/iso646.h \
    $ONRAMP_BIN/../../final/include/math.h:output/final/include/math.h \
    $ONRAMP_BIN/../../final/include/errno.h:output/final/include/errno.h \
    $ONRAMP_BIN/../../final/include/termios.h:output/final/include/termios.h \
    $ONRAMP_BIN/../../final/include/stdbit.h:output/final/include/stdbit.h \
    $ONRAMP_BIN/../../final/include/stdio.h:output/final/include/stdio.h \
    $ONRAMP_BIN/../../final/include/stdarg.h:output/final/include/stdarg.h \
    $ONRAMP_BIN/../../final/include/assert.h:output/final/include/assert.h \
    $ONRAMP_BIN/../../final/include/stdint.h:output/final/include/stdint.h \
    $ONRAMP_BIN/../../final/include/string.h:output/final/include/string.h \
    $ONRAMP_BIN/../../final/lib/libc.oa:output/final/lib/libc.oa \
